### PR TITLE
Karma leaderboard should not including scores of 0 or less

### PR DESCRIPTION
**Pull request by jcorrado**
ref: issue #778

### CODE REVIEW

**Comment by jcorrado** [comment]
CI should pass when @devth merges PR yetibot/yetibot.core#54 and we bump the version dep here.

**Comment by jcorrado** [comment]
This tested good, locally, with `yetibot.core-0.4.53-SNAPSHOT-jcorrado` artifact.

**Comment by devth** [comment]
`yetibot.core 0.4.53` is available with your `HAVING` change!

**Comment by jcorrado** [comment]
Thanks, @devth!  Tested good locally; just pushed bumped version dep.

**Pull request merged**
