### PR TITLE
Migrate from clojure.test to midje

### PR DESCRIPTION
**Pull request by dawsonfi**
Hi,

With this PR, i've changed the test framework from clojure.test to [midje](https://github.com/marick/Midje).

The main purpose of this change, is because of some advantages that i've seen on midje:

* More detailed failing tests output. (Good [source](http://jakemccrary.com/blog/2014/06/22/comparing-clojure-testing-libraries-output/) comparing the output os different test libs).
* Rich [checkers](https://github.com/marick/Midje/wiki/Checkers) ecosystem. Witch helps to write more cleaner and easy to understand tests.
* Easier to [mock](https://github.com/marick/Midje/wiki/Checkers-within-prerequisites) some functions 

Hope you like the change :)

### CODE REVIEW

**Comment by devth** [comment]
Hi @dawsonfi, I've reviewed this several times over the last few weeks but haven't felt strongly about benefits of Midje vs the simplicity of clojure.test. Are you still interested in having this merged? If so I can merge and we'll try it out for awhile since the change is fairly small and easily revertible if we ever wanted to go back.

**Comment by dawsonfi** [comment]
Hi @devth,

Yes, i would really love the opportunity to have midje in this project.
And if you want to give it a try, and later go back, i would gladly help you with that.

Thanks,

**Comment by devth** [comment]
@dawsonfi great! I will merge and we'll try it out for awhile :)

**Comment by dawsonfi** [comment]
Thanks @devth. 

Do you want me to fix the conflicts?

**Comment by devth** [comment]
@dawsonfi it's ok, I fixed it just now.

**Comment by devth** [comment]
This is breaking my vim-fireplace workflow since Midje doesn't include a `(run-tests)` function. Debating whether I want to hack it in or switch back to `clojure.test` 🤔

**Pull request merged**
