### PR TITLE
Add missing dep for yetibot.api.aws

### LINKED ISSUE #905: Missing dep in `yetibot.commands.aws.formatters` breaks Midje autotesting
```
~/projects/yetibot/yetibot master
❯ lein midje :autotest                                                                                 
Warning: implicit hook found: lein-environ.plugin/hooks                                                
Hooks are deprecated and will be removed in a future version.                                          
WARNING: any? already refers to: #'clojure.core/any? in namespace: leiningen.midje, being replaced by: #'leiningen.midje/any?                              
                                                                                                        
======================================================================                                 
Loading ...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".                            
SLF4J: Defaulting to no-operation (NOP) logger implementation                                               
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.          
19-03-29 16:20:44 elder-whale INFO [yetibot.commands.clojure:19] - Clojail erroed java.util.concurrent.ExecutionException: Syntax error compiling at (0:0).
LOAD FAILURE for yetibot.commands.aws.formatters                                                         
clojure.lang.Compiler$CompilerException: Syntax error compiling at (yetibot/commands/aws/formatters.clj:7:24).
    data: #:clojure.error{:phase :compile-syntax-check,                                        
                          :line 7,                                                                 
                          :column 24,                                                              
                          :source "yetibot/commands/aws/formatters.clj"}                           
       java.lang.ClassNotFoundException: yetibot.api.aws                                           
                                           java.net.URLClassLoader.findClass  URLClassLoader.java:  382
                                                                         ...                                                
```

### PR DESCRIPTION
**Pull request by jcorrado**
Closes #905

### CODE REVIEW

**Comment by jcorrado** [comment]
@devth - do you know what's up with that Travis check?
`continuous-integration/travis-ci Expected — Waiting for status to be reported`

**Comment by kaffein** [comment]
💯 sorry for missing this one guys!!
I had a busy week at work :(

thanks for the fix @jcorrado 👍

**Comment by jcorrado** [comment]
@kaffein, no trouble at all!  The test suite ran clean - it was only when using Midje's `:autotest`, which loads things with greater isolation, that I even noticed.  And if you're wondering why I removed you as a reviewer, it had nothing to do with your response time.  I was trying to figure out why that one Travis check is (still) stuck :laughing: .

**Comment by devth** [comment]
I think stuck Travis is related to migrating to the new checks based CI. I’ll debug tomorrow!

**Comment by devth** [comment]
@jcorrado I removed the old Travis integration in favor of the new Checks on travis-ci.com (instead of travis-ci.org), so you're good to merge when ready.

**Comment by jcorrado** [comment]
@devth I don't have permission to merge this, it seems.

**Comment by devth** [comment]
One second, I was playing with the Settings and must have messed something up this morning.

**Comment by devth** [comment]
@jcorrado try now?

**Pull request merged**
