### PR TITLE
Implement !time command.

### LINKED ISSUE #830: ask yetibot what time it is in its configured timezone
```!time```

### PR DESCRIPTION
**Pull request by sarg**
Command returns formatted date time in server timezone.
Closes #830.

### CODE REVIEW

**Comment by sarg** [comment]
Yeah, sure.

**Comment by devth** [comment]
Great. I'd probably add a command to list available timezones too.

Something like:

```
time # return time in default timezone
time zones # list all known time zones (I assume clj-time provides a way to get these. If not, java does)
time <timezone> # return time in given timezone
```

**Comment by sarg** [comment]
`!time zones` result is too big (593 items) for IRC adapter. Seems that #844 should solve that issue.

**Comment by devth** [comment]
Wow. Didn't realize it'd be so long. People can pipe it to grep, or we could add another command:

```
!time zones <pattern> # list time zones matching regex <pattern> 
```

Or just pipe it to grep. I don't think we'd ever want to display that many lines in IRC, even if we did have the throttling solution.

**Comment by sarg** [comment]
What would you suggest? Maybe there should be some safety measure when outputting long collections?

**Comment by devth** [comment]
I think we can output the full list. It's up to the adapter to limit how many lines it prints. Slack is a little better about collapsing long content.

**Pull request merged**
